/******************************************************************************
 *This along with sample_auto_auth_text.c,, these two files are generated from the secure text file sample_auto_auth_text.xml; demonstrates secure, in-memory, text strings.
 *
 * Encoded text
 *
 * Auto generated by uxlMsg ... do not edit
******************************************************************************/

#ifndef UXP_Sample_TEXT_H
#define UXP_Sample_TEXT_H

#include "uxlcommon.h"

#ifdef __cplusplus
extern "C"
{
#endif

/* Define keys identifiers */ 

#define SAMPLE_T_CH0                  1
#define SAMPLE_T_CH1                  2
#define SAMPLE_T_CH2                  3
#define SAMPLE_T_CH3                  4
#define SAMPLE_T_CH4                  5
#define SAMPLE_T_CH5                  6
#define SAMPLE_T_CH6                  7
#define SAMPLE_T_CH7                  8
#define SAMPLE_T_CH8                  9
#define SAMPLE_T_CH9                  10
#define SAMPLE_T_RS0                  11
#define SAMPLE_T_RS1                  12
#define SAMPLE_T_RS2                  13
#define SAMPLE_T_RS3                  14
#define SAMPLE_T_RS4                  15
#define SAMPLE_T_RS5                  16
#define SAMPLE_T_RS6                  17
#define SAMPLE_T_RS7                  18
#define SAMPLE_T_RS8                  19
#define SAMPLE_T_RS9                  20
#define SAMPLE_T_USER                 21

/**
 * @brief Loads secure strings
 */

/* Loads secure string */

UXPLB_HIDDEN void sample_auto_text_init();

#ifdef __cplusplus
}
#endif

#endif
